### ISSUE TITLE
NAV and LANDING light missing

### ISSUE THREAD

**Issue by tonghuix** [it0uchpods/A320Family#1]
![fgfs-screen-092](https://cloud.githubusercontent.com/assets/423703/22852409/9ea2f010-f076-11e6-8a10-5d01ae5bf1e8.png)

![fgfs-screen-091](https://cloud.githubusercontent.com/assets/423703/22852419/d2f85c06-f076-11e6-9017-df3ce0b4a60a.png)

I do confirm turn it on, but NAV light not shown,

**Comment by it0uchpods** [comment]
Thanks for the report.

**Comment by tonghuix** [comment]
@it0uchpods Hi, the landing lights are missing too...

**Comment by it0uchpods** [comment]
Yes those I know. I eilk be redoing them.

**Comment by it0uchpods** [comment]
They should be working now, can you confirm?

**Comment by tonghuix** [comment]
Nope, still not appear.

**Comment by it0uchpods** [comment]
OK, thanks,
I'm on vacation, and don't have access to some of my programs from my laptop, so I'll fix that next week.
Regards,
Josh

**Comment by tonghuix** [comment]
Hi @it0uchpods 

NAV light works perfectly, but LANDING light and TAXI light not works.

**Comment by it0uchpods** [comment]
ALS secondary lights need to be enabled. I'll add the old lights for non ALS systems.

**Comment by YV3399** [comment]
@tonghuix For me if they work.
 These are the lights of now that are already enabled in the a320 of it0uchpods 
  http://imgur.com/a/5G8wv   
soo I'm working on a new system of ALS Will be very complete They'll be ready soon.
Regards Gabriel Hernandez

**Comment by it0uchpods** [comment]
They should be working now. If not, please open a new Issue. The old lights are coming very soon.

**Comment by tonghuix** [comment]
Hi all, all light working perfectly!
