### ISSUE TITLE
FGPropertyValue::GetValue() error on run

### ISSUE THREAD

**Issue by danten66** [it0uchpods/A320Family#10]
Migrating the discussion here...

Previous Errors Fixed: 
FGPropertyValue::GetValue() The Property /it-autoflight/output/ap1 does not exist
FGPropertyValue::GetValue() The property /controls/flight/elevator-fbw does not exist

Latest
4/17/2017 - 21:16pm EST
FGPropertyValue::GetValue() The Property /controls/engines/engine[0]/throttle-fdm does not exist

Running FG 2017.3.1
Downloaded this aircraft as a zip and unpacked into a folder linked to 'additional aircraft locations' on the FG start / Add-Ons tab

**Comment by it0uchpods** [comment]
Woah, 2017.3 must load the FDM way before nasal.... fuck.

Fixed 0140Z

-J

**Comment by it0uchpods** [comment]
Whoops
Keep posting any here until it loads!

Thanks
J

**Comment by danten66** [comment]
Well,  Now we load but a new issue - I have no model.  I only have the Yellow and Blue Glider on the 319.  Trying the 320... and the same.  On a whim, tried the 'pushback vehicle' and no model showed up either.

**Comment by danten66** [comment]
Disregard - re-named Folder from A320Family-Master to A320Family and now it looks like I have something to play with :)

**Comment by it0uchpods** [comment]
:) Have fun!

**Comment by danten66** [comment]
Sorry, I don't know why I would have been assigned this, I'm not a
programmer

Dan

Interested in Genealogy? www.DiscoveringYourPast.com - a Genealogy
Television Show and Journal

**Comment by it0uchpods** [comment]
Hey Dan
We are overhauling the way we do issues, so we assign the reporter to the issue also. We are also back working these to previous issues.

Kind Regards,
Josh

**Comment by danten66** [comment]
Ahh, got it.

Dan

Interested in Genealogy? www.DiscoveringYourPast.com - a Genealogy
Television Show and Journal
