### ISSUE TITLE
A320Family-Master 

### ISSUE THREAD

**Issue by NC-687** [it0uchpods/A320Family#11]
Hey Josh, I downloaded your planes and unfortunately,all I get is a Blue/Yellow glider, I am using 2017.1.2 on a Linux Deb based machine.
The Pushback works though lol :)
NC-687.

**Comment by it0uchpods** [comment]
Have you renamed it A320Family?

It must be called A320Family

Git automatically adds -master to every file.

**Comment by NC-687** [comment]
Hey! yes, renamed and they fly like a bird, I had renamed the original zip
first time and didn't realise that the unzipped was also named Master until
you mentioned it :p
Thanks again for your help !!
Kev.

**Comment by it0uchpods** [comment]
Great, have fun!

No problem,
Josh
