### ISSUE TITLE
MCDU cannot input anything

### ISSUE THREAD

**Issue by tonghuix** [it0uchpods/A320Family#2]
![fgfs-screen-089](https://cloud.githubusercontent.com/assets/423703/22852423/f871d94e-f076-11e6-97b0-643ac490607c.png)

Here is INIT page , I cannot input anything, it seems some layer of MCDU not shown.

**Comment by it0uchpods** [comment]
Because it's not built yet.
MCDU will be working by V1.0
This is a dev plane, please have your patience.
