### ISSUE TITLE
Movement of reverse thrust 

### ISSUE THREAD

**Issue by tonghuix** [it0uchpods/A320Family#5]
I do believe the movement of reverse thrust for IAEv2500 is wrong. I mean I know it is should backward the fuselage of engines. But now a outside exhaust vent backward at same time, please fix it and add a inner grid texture better.

I found two video for that:

https://www.youtube.com/watch?v=oGigYu3v5XY (1:05 - 1:15)

https://www.youtube.com/watch?v=UqiSAIdfDyw

**Comment by it0uchpods** [comment]
OK I will say this again.

Aircraft is not complete. Please report minor issues on the forums, not here.

I am working SYSTEMS first, then COSMETICS. It will all be fixed by V1.0
