### ISSUE TITLE
Invisible Aircraft

### ISSUE THREAD

**Issue by HHS81** [it0uchpods/A320Family#57]
Obviously it is Wonder Womans A320: it is invisible in FlightGear 2017.3.0

Following error message:
`Failed to load model: Failed to load 3D model:
 at C:/Users/Heiko/FlightGear/GIT/Aircraft/A320Family/Models/empty.ac
        from:C:/Users/Heiko/FlightGear/GIT/Aircraft/A320Family/Models/A320-200-C
FM.xml`

**Comment by it0uchpods** [comment]
Wait wait wait ---------- did you rename it A320Family? Remove the --master?

**Comment by it0uchpods** [comment]
I don't get this issue -- tested

Please confirm you renamed it, I'm closing this for now, since I do not support in development FG releases.

**Comment by HHS81** [comment]
@it0uchpods 
As a FlightGear Aircraft developer with more than 10years experience of course I checked if it has the correct name- which you should have noticed reading then error message I gave you....

And a small hint: as an serious aircraft developer you should consider to use the developement branches to make sure that your aircraft works in the following stable releases....

**Comment by it0uchpods** [comment]
But I don't like using indevelopment versions. Read my comment on the other issue, another person on our dev team said it works -- so...????

Here is what I don't understand: C:/Users/Heiko/FlightGear/GIT/Aircraft/A320Family/Models/A320-200-C FM.xml

There should be no space there. The -set file has no space in it, so I cannot only imagine your unarchiver made an error.

Please check the following:
A320-200-CFM-set.xml
Line 15 should read: <path>Aircraft/A320Family/Models/A320-200-CFM.xml</path>
Inside Modes, you should see a file called A320-200-CFM.xml

Since you are an experienced dev, I'll reopen this, as I doubt it's user error.

Please let me know and report.

Kind Regards,
Josh

**Comment by HHS81** [comment]
Complete error message:

```
Failed to load model: Failed to load 3D model:
 at C:/Users/Heiko/FlightGear/GIT/Aircraft/A320Family/Models/empty.ac
        from:C:/Users/Heiko/FlightGear/GIT/Aircraft/A320Family/Models/A320-100-C
FM.xml
          ____ ___   ___  ______              _ _
    /\   |___ \__ \ / _ \|  ____|            (_) |
   /  \    __) | ) | | | | |__ __ _ _ __ ___  _| |_   _
  / /\ \  |__ < / /| | | |  __/ _` | '_ ` _ \| | | | | |
 / ____ \ ___) / /_| |_| | | | (_| | | | | | | | | |_| |
/_/    \_\____/____|\___/|_|  \__,_|_| |_| |_|_|_|\__, |
                                                   __/ |
                                                  |___/
-----------------------------------------------------------------------
(c) 2016-2017 Joshua Davidson, and Jonathan Redpath
Report all bugs on GitHub Issues tab, or the forums. :)
If you are reading this, you are awesome!
-----------------------------------------------------------------------

Nasal parse error: illegal character in C:/Users/Heiko/FlightGear/GIT/Aircraft/A
320Family/Nasal/a320livery-cfm-100.nas, line 1
ND Canvas Initialized!
```

From A320-200-CFM-set.xml, including line 15:

	
```
<aero>A320-200-CFM</aero>
		<model>
			<path>Aircraft/A320Family/Models/A320-200-CFM.xml</path>
			<livery>
				<file>Airbus</file>
			</livery>
		</model>
```


I did clone it, and did a pull. So no unarchiver used here.

When deleting line 5 	`<path>empty.ac</path> <!-- Livery system on MP multimodel -->` from Models/A320-200-CFM.xml the model appears again.

**Comment by it0uchpods** [comment]
Thanks,
Very interesting.....
Maybe the new FG doesn't allow loading an empty .ac file?
Can you see if the MCDU appears when powering up? It uses the same empty.ac dummy file.

Your pasted console debug shows a space between C and FM up top, I'm guessing that is from the console.

So please check the MCDU, and report back, meanwhile, I'll try to download 2017.3.1.

Kind Regards,
Josh

**Comment by HHS81** [comment]
There is no 2017.3.1 yet, just the developement branch 2017.3.0

MCDU appears, and seems to work.

**Comment by it0uchpods** [comment]
@HHS81 That is what I meant, sorry.

That is really odd........ Perhaps another corupted file as you showed in the other issue?

Can you try cloning again?

**Comment by HHS81** [comment]
o.k., now even with loading empty.ac the aircraft loads well, after a new clone. 

Temporary File corruption with GIT - something new to me. I had those issues in the past when .xml had different line endings etc., 

Anyway, I can enjoy now the Airbus, great work!

**Comment by it0uchpods** [comment]
Have fun! :)

Kind Regards,
Josh
