### ISSUE TITLE
A320 UPPER ECAM FEATURE REQUESTS

### ISSUE THREAD

**Issue by legoboyvdlp** [it0uchpods/A320Family#59]
Feature requests:
**These are for the IAE version, it may be the same for CFM version**

* The XX on N1 goes out at 3.5%. The igniters do not fire until the engine has motored for 30 seconds, thus you only see "A" or "B" on the respective engine (LOWER ECAM) after 30 seconds.
https://youtu.be/XtKuNkNLT1A?t=234

* At 43% N2, the ignition stops and the start valve closes, the engine continues to spin up itself. 
https://youtu.be/XtKuNkNLT1A?t=266

**The following are for CFM, may be for IAE too.**

* For 5 min after elec power is applied the FADEC is powered, thus there are no XX or amber on the EWD. When you selec IGN/START the XX disappears (CFM only). 
(On IAE, the XX for N1 disappears at 3.5% N1, while the EPR XX disappears when you power FADEC).
* At 22% N2, the fuel flow increases
https://youtu.be/nCuhfqifC7k?t=63

**This is for both engines**
* When you move the lever to ON, then the fuel used counter resets. 
* The N2 is displayed on a grey background above 3.5%: it disappears at idle N2 (~60%)
https://youtu.be/XtKuNkNLT1A?t=181

**Comment by it0uchpods** [comment]
There are differences between the IAE and CFM,

CFM XX needs a tweak.
The N1 at 3.5 is modelled already, I will model ignition soon.

Eng startup still looking for a way around the startup time. It should be slower.

See these CBTs, thus is what I am modelling from.
IAE: https://youtu.be/XtKuNkNLT1A
CFM: https://youtu.be/ur5A6Yz2ToE

Kind Regards,
Josh

**Comment by it0uchpods** [comment]
Just realized you already sent those videos, OK!

**Comment by legoboyvdlp** [comment]
WAIT

**Comment by legoboyvdlp** [comment]
Feature requests:
**These are for the IAE version, it may be the same for CFM version**

* The igniters do not fire until the engine has motored for 30 seconds, thus you only see "A" or "B" on the respective engine (LOWER ECAM) after 30 seconds.
https://youtu.be/XtKuNkNLT1A?t=234

* At 43% N2, the ignition stops and the start valve closes, the engine continues to spin up itself. 
https://youtu.be/XtKuNkNLT1A?t=266



**The following are for CFM, may be for IAE too.**

* For 5 min after elec power is applied the FADEC is powered, thus there are no XX or amber on the EWD. When you selec IGN/START the XX disappears (CFM only). 


**This is for both engines**
* When you move the lever to ON, then the fuel used counter resets. 
* The N2 is displayed on a grey background above 3.5%: it disappears at idle N2 (~60%)
https://youtu.be/XtKuNkNLT1A?t=181

**Comment by legoboyvdlp** [comment]
At least do the N2 grey backgroud and "5 min after elec power no XX".

**Comment by it0uchpods** [comment]
Yes, I have my research. Next time, PM it to me, it's nor really an issue.
