### ISSUE TITLE
Might just be a noob 

### ISSUE THREAD

**Issue by Fiyover** [it0uchpods/A320Family#60]
Hi, I might just be a noob or missing something but when i put the planes in my aircraft folder in the flight gear main dir it doesn't load the plane in the game, it just shows the scenery with no plane model or anything. Do I need to install something or is a bug?
![screenshot_12](https://user-images.githubusercontent.com/30011390/27990152-90a5b428-6445-11e7-9a4b-e027276b3c69.png)

**Comment by it0uchpods** [comment]
Hi!
Please rename the folder to A320Family
GIT automatically adds -master.

Kind Regards,
Josh
