### ISSUE TITLE
Gear being really bad at turning

### ISSUE THREAD

**Issue by Fiyover** [it0uchpods/A320Family#61]
Hi, before i take off the turning is really good but when i land i cant even exit the runway because of how bad it is, i go straight into the grass

**Comment by it0uchpods** [comment]
Hi there
This is a known issue, the solution it to break gentler. We are looking for the problem, and will fix it as soon as we found it. 

Kind Regards,
Josh

**Comment by it0uchpods** [comment]
Moved to an internal issue item in the Dev Team, closing this now.
